spring:
  application:
    name: retail-order-management-api
  profiles:
    default: dev
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
